sidebar_icons:
  summary: house
  experience: person
  skills: gear
  education: trophy
  certifications: clipboard-check
  projects: folder
  hobbies: joystick
  employment: person-workspace
section_icons:
  summary: house
  experience: necktie
  skills: male-technologist
  certifications: trophy
  education: school
  projects: open_file_folder
  hobbies: video_game
  employment: office
colors:
  - '#ffc09f'
  - '#ffee93'
  - '#a0ced9'
  - '#95b8d1'
  - '#b8e0d2'
  - '#e8dff5'
  - '#fcf4dd'
  - '#ddedea'
  - '#daeaf6'
  - '#d1cfe2'
  - '#9cadce'
  - '#7ec4cf'
  - '#e69597'
  - '#ceb5b7'
  - '#b5d6d6'
  - '#f6bc66'
  - '#bde0fe'

dark_colors:
  - "#2ab7ca"
  - "#fed766"
  - "#dec3c3"
  - "#3da4ab"
  - "#fe8a71"
  - "#d0e1f9"
  - "#c99789"
  - "#96ceb4"
  - "#ffefd7"
  - "#e4dcf1"
  - "#e0ac69"
  - "#abc4ff"
  - "#d1d1d1"
  - "#809bce"
  - "#9cf6f6"
  - "#f08080"


freq_color: "#2f4550"
