sidebar:
  Summary: house
  Experience: person
  Skills: gear
  Certifications: clipboard-check
  Education: trophy
  Projects: folder
  Hobbies: joystick
sections:
  Summary:
  Experience: male-technologist
  Skills:
  Certifications:
  Education: school
  Projects:
  Hobbies:
colors:
  - '#ffc09f'
  - '#ffee93'
  - '#a0ced9'
  - '#95b8d1'
  - '#b8e0d2'
  - '#e8dff5'
  - '#fcf4dd'
  - '#ddedea'
  - '#daeaf6'
  - '#d1cfe2'
  - '#9cadce'
  - '#7ec4cf'
  - '#e69597'
  - '#ceb5b7'
  - '#b5d6d6'
  - '#f6bc66'
  - '#bde0fe'
freq_color: "#2f4550"
