phone_icon: 'phone.png'
phone_link: callto:+15157351486
phone_text: (515) 735-1486

mail_icon: 'mail.png'
mail_link: mailto:ramana.ambore@gmail.com
mail_text: Ramana.Ambore@gmail.com

medium_icon: 'medium.png'
medium_link: 'https://medium.com/@rrambo'
medium_text: 'medium.com/@rrambo'

github_icon: 'github.png'
github_link: 'https://github.com/RamanaAmbore'
github_text: 'github.com/RamanaAmbore'

linkedin_icon: 'linkedin.png'
linkedin_link: 'https://www.linkedin.com/in/ramanaambore'
linkedin_text: 'linkedin.com/in/ramanaambore'

loc_icon: 'loc.png'
loc_link: 'https://www.google.co.in/maps/place/Wells+Fargo+West+Des+Moines+Campus/@41.5561561,-93.8308645,14z/data=!4m10!1m2!2m1!1sWest+Des+Moines+Campus+s+jordan+creek+pkway!3m6!1s0x87ec21e209c60fc7:0x6a4f0150f22ca0dc!8m2!3d41.5561561!4d-93.8053741!15sCipXZXN0IERlcyBNb2luZXMgQ2FtcHVzIHMgam9yZGFuIGNyZWVrIHBrd3laLCIqd2VzdCBkZXMgbW9pbmVzIGNhbXB1cyBzIGpvcmRhbiBjcmVlayBwa3d5kgEQY29ycG9yYXRlX29mZmljZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VOUFgyTnllbXhCUlJBQuABAPoBBAgVEBE!16s%2Fg%2F11h7pj06qt?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D'
loc_text: West Des Moines, Iowa

streamlit_icon: 'streamlit.png'
streamlit_link: 'https://share.streamlit.io/user/ramanaambore'
streamlit_text: 'share.streamlit.io/user/ramanaambore'






