[theme]
primaryColor="#0f172a"
backgroundColor="#F5F7FA"
secondaryBackgroundColor="#2f4550"
textColor="#315062"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false