[theme]
primaryColor="#315062"
backgroundColor="#F5F7FA"
secondaryBackgroundColor="#2f4550"
textColor="#0A172A"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false