[theme]
primaryColor="#f15233"
backgroundColor="#ffffff"
secondaryBackgroundColor="#2f4550"
textColor="#0c3b4b"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false