[theme]
primaryColor="#E66414"
backgroundColor="white"
secondaryBackgroundColor="#FAFEFF"
textColor="315062"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false