[theme]
primaryColor="#315062"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FAFEFF"
textColor="#0A172A"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false