[theme]
primaryColor="#0f172a"
backgroundColor="#f8fafc"
secondaryBackgroundColor="#2f4550"
textColor="#666"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false