[theme]
primaryColor="#2f4f4f"
backgroundColor="#f7f7f5"
secondaryBackgroundColor="black"
textColor="#315062"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true

[client]
showSidebarNavigation = false